services:
  - type: web
    name: gymmanager
    runtime: docker
    plan: free
    healthCheckPath: /login
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        value: gym_manager
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_CHARSET
        value: utf8mb4