<?php $basePath=defined('BASE_PATH')?BASE_PATH:''; include dirname(__DIR__).'/layouts/header.php'; ?>
<div class="page-head"><div><h1 class="page-title">Editar Treino</h1><p class="subtitle">Atualize o treino e seu acompanhamento.</p></div></div>
<div class="card"><?php if(!empty($erros)):?><div class="alert alert-danger"><ul><?php foreach($erros as $erro):?><li><?=htmlspecialchars((string)$erro)?></li><?php endforeach;?></ul></div><?php endif;?>
<form action="<?=$basePath?>/treinos/update" method="post"><?=Security::campoCSRF()?><input type="hidden" name="id" value="<?=(int)$treino['id']?>"><div class="form-grid">
<div class="form-group"><label class="form-label">Aluno</label><select class="form-control" name="aluno_id" required><?php foreach($alunos as $a):?><option value="<?=(int)$a['id']?>" <?=((int)$treino['aluno_id']===(int)$a['id'])?'selected':''?>><?=htmlspecialchars((string)$a['nome'])?></option><?php endforeach;?></select></div>
<div class="form-group"><label class="form-label">Professor responsável</label><select class="form-control" name="professor_id" required><?php foreach($professores as $p):?><option value="<?=(int)$p['id']?>" <?=((int)$treino['professor_id']===(int)$p['id'])?'selected':''?>><?=htmlspecialchars((string)$p['nome'])?></option><?php endforeach;?></select></div>
<div class="form-group"><label class="form-label">Nome do treino</label><input class="form-control" name="nome" required value="<?=htmlspecialchars((string)($treino['nome']??''))?>"></div>
<div class="form-group"><label class="form-label">Objetivo</label><input class="form-control" name="objetivo" value="<?=htmlspecialchars((string)($treino['objetivo']??''))?>"></div>
<div class="form-group"><label class="form-label">Data de início</label><input class="form-control" type="date" name="data_inicio" required value="<?=htmlspecialchars((string)($treino['data_inicio']??''))?>"></div>
<div class="form-group"><label class="form-label">Data de término</label><input class="form-control" type="date" name="data_fim" value="<?=htmlspecialchars((string)($treino['data_fim']??''))?>"></div>
<div class="form-group"><label class="form-label">Status</label><select class="form-control" name="status"><option value="ativo" <?=($treino['status']??'')==='ativo'?'selected':''?>>Ativo</option><option value="finalizado" <?=($treino['status']??'')==='finalizado'?'selected':''?>>Finalizado</option></select></div>
<div class="form-group" style="grid-column:1/-1"><label class="form-label">Exercícios / observações</label><textarea class="form-control" rows="7" name="descricao"><?=htmlspecialchars((string)($treino['descricao']??''))?></textarea></div>
</div><div class="form-actions"><button class="btn btn-primary">Salvar</button><a class="btn btn-secondary" href="<?=$basePath?>/treinos">Cancelar</a></div></form></div>
<?php include dirname(__DIR__).'/layouts/footer.php'; ?>