<?php $basePath=defined('BASE_PATH')?BASE_PATH:''; include dirname(__DIR__).'/layouts/header.php'; ?>
<div class="page-head"><div><h1 class="page-title">Nova Matrícula</h1><p class="subtitle">Vincule um aluno a um plano.</p></div></div>
<div class="card"><?php if(!empty($erros)):?><div class="alert alert-danger"><ul><?php foreach($erros as $erro):?><li><?=htmlspecialchars((string)$erro)?></li><?php endforeach;?></ul></div><?php endif;?>
<form action="<?=$basePath?>/matriculas/store" method="post"><?=Security::campoCSRF()?><div class="form-grid">
<div class="form-group"><label class="form-label">Aluno</label><select class="form-control" name="aluno_id" required><option value="">Selecione</option><?php foreach($alunos as $a):?><option value="<?=(int)$a['id']?>" <?=((string)($dados['aluno_id']??''))===(string)$a['id']?'selected':''?>><?=htmlspecialchars((string)$a['nome'])?></option><?php endforeach;?></select></div>
<div class="form-group"><label class="form-label">Plano</label><select class="form-control" name="plano_id" required><option value="">Selecione</option><?php foreach($planos as $p):?><option value="<?=(int)$p['id']?>" <?=((string)($dados['plano_id']??''))===(string)$p['id']?'selected':''?>><?=htmlspecialchars((string)$p['nome'])?> — R$ <?=number_format((float)$p['valor'],2,',','.')?></option><?php endforeach;?></select></div>
<div class="form-group"><label class="form-label">Data de início</label><input class="form-control" type="date" name="data_inicio" required value="<?=htmlspecialchars((string)($dados['data_inicio']??''))?>"></div>
<div class="form-group"><label class="form-label">Data de término</label><input class="form-control" type="date" name="data_fim" required value="<?=htmlspecialchars((string)($dados['data_fim']??''))?>"></div>
<div class="form-group"><label class="form-label">Status</label><select class="form-control" name="status"><option value="ativa" <?=($dados['status']??'')==='ativa'?'selected':''?>>Ativa</option><option value="vencida" <?=($dados['status']??'')==='vencida'?'selected':''?>>Vencida</option><option value="cancelada" <?=($dados['status']??'')==='cancelada'?'selected':''?>>Cancelada</option></select></div>
</div><div class="form-actions"><button class="btn btn-primary">Salvar</button><a class="btn btn-secondary" href="<?=$basePath?>/matriculas">Cancelar</a></div></form></div>
<?php include dirname(__DIR__).'/layouts/footer.php'; ?>