<?php $basePath=defined('BASE_PATH')?BASE_PATH:''; include dirname(__DIR__).'/layouts/header.php'; ?>
<div class="page-head"><div><h1 class="page-title">Editar Matrícula</h1><p class="subtitle">Atualize plano, período e status da matrícula.</p></div></div>
<div class="card"><?php if(!empty($erros)):?><div class="alert alert-danger"><ul><?php foreach($erros as $erro):?><li><?=htmlspecialchars((string)$erro)?></li><?php endforeach;?></ul></div><?php endif;?>
<form action="<?=$basePath?>/matriculas/update" method="post"><?=Security::campoCSRF()?><input type="hidden" name="id" value="<?=(int)$matricula['id']?>"><div class="form-grid">
<div class="form-group"><label class="form-label">Aluno</label><select class="form-control" name="aluno_id" required><?php foreach($alunos as $a):?><option value="<?=(int)$a['id']?>" <?=((int)$matricula['aluno_id']===(int)$a['id'])?'selected':''?>><?=htmlspecialchars((string)$a['nome'])?></option><?php endforeach;?></select></div>
<div class="form-group"><label class="form-label">Plano</label><select class="form-control" name="plano_id" required><?php foreach($planos as $p):?><option value="<?=(int)$p['id']?>" <?=((int)$matricula['plano_id']===(int)$p['id'])?'selected':''?>><?=htmlspecialchars((string)$p['nome'])?></option><?php endforeach;?></select></div>
<div class="form-group"><label class="form-label">Data de início</label><input class="form-control" type="date" name="data_inicio" required value="<?=htmlspecialchars((string)$matricula['data_inicio'])?>"></div>
<div class="form-group"><label class="form-label">Data de término</label><input class="form-control" type="date" name="data_fim" required value="<?=htmlspecialchars((string)$matricula['data_fim'])?>"></div>
<div class="form-group"><label class="form-label">Status</label><select class="form-control" name="status"><option value="ativa" <?=($matricula['status']??'')==='ativa'?'selected':''?>>Ativa</option><option value="vencida" <?=($matricula['status']??'')==='vencida'?'selected':''?>>Vencida</option><option value="cancelada" <?=($matricula['status']??'')==='cancelada'?'selected':''?>>Cancelada</option></select></div>
</div><div class="form-actions"><button class="btn btn-primary">Salvar</button><a class="btn btn-secondary" href="<?=$basePath?>/matriculas">Cancelar</a></div></form></div>
<?php include dirname(__DIR__).'/layouts/footer.php'; ?>