<?php $basePath=defined('BASE_PATH')?BASE_PATH:''; include dirname(__DIR__).'/layouts/header.php'; ?>
<div class="page-head"><div><h1 class="page-title">Cadastrar Novo Usuário</h1><p class="subtitle">Defina credenciais, perfil e situação de acesso.</p></div></div>
<div class="card"><?php if(!empty($erros)):?><div class="alert alert-danger"><ul><?php foreach($erros as $erro):?><li><?=htmlspecialchars((string)$erro)?></li><?php endforeach;?></ul></div><?php endif;?>
<form action="<?=$basePath?>/usuarios/store" method="post"><?=Security::campoCSRF()?><div class="form-grid">
<div class="form-group"><label class="form-label">Nome completo</label><input class="form-control" name="nome" required value="<?=htmlspecialchars((string)($dados['nome']??''))?>"></div>
<div class="form-group"><label class="form-label">E-mail</label><input class="form-control" type="email" name="email" required value="<?=htmlspecialchars((string)($dados['email']??''))?>"></div>
<div class="form-group"><label class="form-label">Senha</label><input class="form-control" type="password" name="senha" minlength="6" required></div>
<div class="form-group"><label class="form-label">Confirmar senha</label><input class="form-control" type="password" name="confirmar_senha" minlength="6" required></div>
<div class="form-group"><label class="form-label">Perfil de acesso</label><select class="form-control" name="perfil"><option value="atendente" <?=($dados['perfil']??'')==='atendente'?'selected':''?>>Recepcionista</option><option value="professor" <?=($dados['perfil']??'')==='professor'?'selected':''?>>Professor</option><option value="administrador" <?=($dados['perfil']??'')==='administrador'?'selected':''?>>Administrador</option></select></div>
<div class="form-group"><label class="form-label">Status</label><select class="form-control" name="status"><option value="ativo" <?=($dados['status']??'')==='ativo'?'selected':''?>>Ativo</option><option value="inativo" <?=($dados['status']??'')==='inativo'?'selected':''?>>Inativo</option></select></div>
</div><div class="form-actions"><button class="btn btn-primary">Salvar</button><a class="btn btn-secondary" href="<?=$basePath?>/usuarios">Cancelar</a></div></form></div>
<?php include dirname(__DIR__).'/layouts/footer.php'; ?>