<?php $basePath=defined('BASE_PATH')?BASE_PATH:''; include dirname(__DIR__).'/layouts/header.php'; ?>
<div class="page-head"><div><h1 class="page-title">Editar Usuário</h1><p class="subtitle">Atualize dados, perfil, status ou senha.</p></div></div>
<div class="card"><?php if(!empty($erros)):?><div class="alert alert-danger"><ul><?php foreach($erros as $erro):?><li><?=htmlspecialchars((string)$erro)?></li><?php endforeach;?></ul></div><?php endif;?>
<form action="<?=$basePath?>/usuarios/update" method="post"><?=Security::campoCSRF()?><input type="hidden" name="id" value="<?=(int)$usuario['id']?>"><div class="form-grid">
<div class="form-group"><label class="form-label">Nome completo</label><input class="form-control" name="nome" required value="<?=htmlspecialchars((string)($usuario['nome']??''))?>"></div>
<div class="form-group"><label class="form-label">E-mail</label><input class="form-control" type="email" name="email" required value="<?=htmlspecialchars((string)($usuario['email']??''))?>"></div>
<div class="form-group"><label class="form-label">Nova senha</label><input class="form-control" type="password" name="senha" minlength="6" placeholder="Deixe em branco para manter"></div>
<div class="form-group"><label class="form-label">Confirmar nova senha</label><input class="form-control" type="password" name="confirmar_senha" minlength="6"></div>
<div class="form-group"><label class="form-label">Perfil de acesso</label><select class="form-control" name="perfil"><option value="atendente" <?=($usuario['perfil']??'')==='atendente'?'selected':''?>>Recepcionista</option><option value="professor" <?=($usuario['perfil']??'')==='professor'?'selected':''?>>Professor</option><option value="administrador" <?=($usuario['perfil']??'')==='administrador'?'selected':''?>>Administrador</option></select></div>
<div class="form-group"><label class="form-label">Status</label><select class="form-control" name="status"><option value="ativo" <?=($usuario['status']??'')==='ativo'?'selected':''?>>Ativo</option><option value="inativo" <?=($usuario['status']??'')==='inativo'?'selected':''?>>Inativo</option></select></div>
</div><div class="form-actions"><button class="btn btn-primary">Salvar</button><a class="btn btn-secondary" href="<?=$basePath?>/usuarios">Cancelar</a></div></form></div>
<?php include dirname(__DIR__).'/layouts/footer.php'; ?>