<?php $basePath=defined('BASE_PATH')?BASE_PATH:''; include dirname(__DIR__).'/layouts/header.php'; ?>
<div class="page-head"><div><h1 class="page-title">Editar Pagamento</h1><p class="subtitle">Atualize vencimento, pagamento, forma e situação.</p></div></div>
<div class="card"><?php if(!empty($erros)):?><div class="alert alert-danger"><ul><?php foreach($erros as $erro):?><li><?=htmlspecialchars((string)$erro)?></li><?php endforeach;?></ul></div><?php endif;?>
<form action="<?=$basePath?>/pagamentos/update" method="post"><?=Security::campoCSRF()?><input type="hidden" name="id" value="<?=(int)$pagamento['id']?>"><div class="form-grid">
<div class="form-group"><label class="form-label">Matrícula</label><select class="form-control" name="matricula_id" required><?php foreach($matriculas as $m):?><option value="<?=(int)$m['id']?>" <?=((int)$pagamento['matricula_id']===(int)$m['id'])?'selected':''?>><?=htmlspecialchars((string)$m['aluno_nome'])?> — <?=htmlspecialchars((string)$m['plano_nome'])?></option><?php endforeach;?></select></div>
<div class="form-group"><label class="form-label">Valor (R$)</label><input class="form-control" type="number" min="0.01" step="0.01" name="valor" required value="<?=htmlspecialchars((string)$pagamento['valor'])?>"></div>
<div class="form-group"><label class="form-label">Data de vencimento</label><input class="form-control" type="date" name="data_vencimento" required value="<?=htmlspecialchars((string)$pagamento['data_vencimento'])?>"></div>
<div class="form-group"><label class="form-label">Data de pagamento</label><input class="form-control" type="date" name="data_pagamento" value="<?=htmlspecialchars((string)($pagamento['data_pagamento']??''))?>"></div>
<div class="form-group"><label class="form-label">Forma de pagamento</label><select class="form-control" name="forma_pagamento"><option value="">Não informada</option><?php foreach(['dinheiro'=>'Dinheiro','pix'=>'Pix','cartao'=>'Cartão','boleto'=>'Boleto'] as $v=>$l):?><option value="<?=$v?>" <?=($pagamento['forma_pagamento']??'')===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></div>
<div class="form-group"><label class="form-label">Situação</label><select class="form-control" name="status"><?php foreach(['pendente'=>'Pendente','pago'=>'Pago','atrasado'=>'Atrasado','cancelado'=>'Cancelado'] as $v=>$l):?><option value="<?=$v?>" <?=($pagamento['status']??'')===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></div>
</div><div class="form-actions"><button class="btn btn-primary">Salvar</button><a class="btn btn-secondary" href="<?=$basePath?>/pagamentos">Cancelar</a></div></form></div>
<?php include dirname(__DIR__).'/layouts/footer.php'; ?>